force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>Crt-{0000}</displayFormat>
        <label>Cart #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open,</fullName>
            </value>
            <value>
                <fullName>Closed,</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Cart_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Itm-{0000}</displayFormat>
        <label>Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>The Amount for the single item record</inlineHelpText>
    <label>Amount</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <inlineHelpText>The parent cart under which the item is added</inlineHelpText>
    <label>Cart Id</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>cart Items</relationshipLabel>
    <relationshipName>cart_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The product record which is added as item under the cart record</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>cart Items</relationshipLabel>
    <relationshipName>cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>The total no of items to be included into the cart</inlineHelpText>
    <label>Quantity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>Quantity__c  *  Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total amount for the item record</inlineHelpText>
    <label>TotalAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <inlineHelpText>The Selling Price of the Product</inlineHelpText>
    <label>UnitPrice</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Image__c/Product_Image__c.object-meta.xml
<CustomObject>
    <label>Product Image</label>
    <nameField>
        <label>product image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Image__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <inlineHelpText>Required if Static Resource is Selected in Image Type</inlineHelpText>
    <label>Static Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Image__c/fields/ResourceURL__c.field-meta.xml
<CustomField>
    <fullName>ResourceURL__c</fullName>
    <inlineHelpText>Contains the fully Qualified Path of the image to be shown on the product detail page</inlineHelpText>
    <label>Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductImagesApexClass.cls
public with sharing class ProductImagesApexClass {
@AuraEnabled(cacheable=true)
public static List<Product_Image__c> getProductsImages(String searchKey){ 
    if(searchKey !=''){
        String key='%'+searchKey+'%';
        List<Product_Image__c> pcList1 = [SELECT Id,Product__r.Name,Product__r.Id,Product__r.RemainingQuantity__c,Product__r.Description,Product__c,HeroImage__c,Name,ResourceURL__c,Resource__c FROM Product_Image__c WHERE ResourceURL__c !='' AND Product__r.Name LIKE:key ]; 
        return pcList1;
    }
    else
    {
        List<Product_Image__c> pcList2 = [SELECT Id,Product__r.Name,Product__r.Id,Product__r.RemainingQuantity__c,Product__r.Description,Product__c,HeroImage__c,Name,ResourceURL__c,Resource__c FROM Product_Image__c WHERE ResourceURL__c !='' ]; 
        if(!pcList2.isEmpty()){
        return pcList2;
        }                       
        return NULL;
        } 
    }

    @auraEnabled(cacheable=true) 
    public static List<Product_Image__c> getProductDetail(){ 
        List<Product_Image__c> pcList = [SELECT Id,Product__r.Name,Product__r.Id,URL__c,Product__c,Resource__c,ResourceURL__c FROM Product_Image__c WHERE Id='a0r1e00000153ZaAAI' ];                   
        return pcList; 
   } 

   @AuraEnabled(cacheable=true) 
	public static string getItems(String cartId){
        List<Cart_Item__c> items = [SELECT Id, Name, Product__c, Cart__c,Quantity__c, UnitPrice__c,TotalAmount__c,Product__r.Name FROM Cart_Item__c WHERE Cart__c =: cartId];
        return JSON.serialize(items);
    }
    public Static Map<Id, Cart_Item__c> getCartItems(String cartId){
        Map<Id, Cart_Item__c> cartItemsMap = new Map<Id, Cart_Item__c>();
        for ( Cart_Item__c cart :[SELECT Id, Name, Product__c, Cart__c,Quantity__c, UnitPrice__c,TotalAmount__c,Product__r.Name FROM Cart_Item__c WHERE Cart__c =: cartId]) {
            cartItemsMap.put(cart.Product__c, cart);
        }
        return cartItemsMap;
    }

    
   public static String generateCardId(){
    String CharList = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_';
    Integer position;
    Integer LengthRequired = 30;
    String Res = '';
    for(Integer i = 0; i <= LengthRequired; i++) {
        position = Integer.valueof(String.valueof(Math.roundToLong(CharList.length()*Math.random()))) -1;
        Res += CharList.substring(position,position+1);
    }
    return Res;
}

   //Create Cart
    /*@AuraEnabled(cacheable=false)
    public static string getCartId(){
    List<Cart__c> cartInfo = [SELECT Id, Name,User__c FROM Cart__c WHERE User__c =: UserInfo.getUserId() AND Status__c= 'Open'];
    if (cartInfo != null && cartInfo.size() > 0) {
        return cartInfo.get(0).Id;              
    } else { 
        Cart__c defaultCart = new Cart__c();
        //Coupon__c coupon = getCouponInformation('Default');
        defaultCart.CartId__c = generateCardId();
        defaultCart.Status__c = 'Open';
        //defaultCart.User__c = UserInfo.getUserId();
        insert defaultCart;
       system.debug('id : '+defaultCart.Id);
        return defaultCart.Id;
    }                        
}*/

public class CartWrapper {
    @AuraEnabled
    public String CartId                { get; set; }
    @AuraEnabled
    public Decimal Count                { get; set; }
    @AuraEnabled
    public List<Cart_Item__c> items     { get; set; }
}

@AuraEnabled
public static string createCartItems(String CartId, String ProductId, Decimal Amount,Integer Quantity){
    Cart_Item__c item = new Cart_Item__c();
    Map<Id, Cart_Item__c> cartItemsMap = getCartItems(CartId);
    if ( cartItemsMap.containsKey(ProductId) ) {
        item = cartItemsMap.get(ProductId);
        item.Quantity__c = item.Quantity__c + 1;
        update item;
    } else {
        item.Product__c = ProductId;
        item.Cart__c = CartId;
        item.Quantity__c = Quantity ;
        item.UnitPrice__c = Amount;
        item.Amount__c = Amount;
        insert item;
    }
    return item.Id;
 }

}