force-app/main/default/objects/Categories__c/Categories__c.object-meta.xml
<CustomObject>
    <description>Custom objects hold the name of the category to which the product will be associated.</description>
    <label>Categories</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Categories__c/fields/ParentCategory__c.field-meta.xml
<CustomField>
    <fullName>ParentCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The parent category if this is the child category.</inlineHelpText>
    <label>Parent Category</label>
    <referenceTo>Categories__c</referenceTo>
    <relationshipName>Categorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Categories__c/Product_Categories__c.object-meta.xml
<CustomObject>
    <description>Custom salesforce object which will be the child of category and product to link product and category.</description>
    <label>Product Categories</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Product Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Categories__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>The category for the product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Categories__c</referenceTo>
    <relationshipName>Product_Categorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Categories__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The product for the category.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Categorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Categoryclass.cls
public with sharing class Categoryclass 
{
    @AuraEnabled(cacheable=true)
    Public static List<Categories__c> getparentcategory()
    {
        Return [SELECT Name FROM Categories__c];
    }
    
    @AuraEnabled(cacheable=true)
    Public static List<Categories__c> getCategory(string parentid)
    {
       return [SELECT Name, ParentCategory__c FROM Categories__c where ParentCategory__c=:parentid];
    }
    
    @AuraEnabled(cacheable=true)
    Public static List<Product_Categories__c> getProductCategory(string catid)
    {
        return [SELECT Category__c, Product__r.Name FROM Product_Categories__c where Category__c=:catid];
    } 
}