force-app/main/default/objects/Categories__c/Categories__c.object-meta.xml
<CustomObject>
    <description>Custom objects hold the name of the category to which the product will be associated.</description>
    <label>Categories</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Categories__c/fields/ParentCategory__c.field-meta.xml
<CustomField>
    <fullName>ParentCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The parent category if this is the child category.</inlineHelpText>
    <label>Parent Category</label>
    <referenceTo>Categories__c</referenceTo>
    <relationshipName>Categorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Categories__c/Product_Categories__c.object-meta.xml
<CustomObject>
    <description>Custom salesforce object which will be the child of category and product to link product and category.</description>
    <label>Product Categories</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Product Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Categories__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>The category for the product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Categories__c</referenceTo>
    <relationshipName>Product_Categorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CategoryRelatedRecords.cls
public with sharing class CategoryRelatedRecords 
{
    @AuraEnabled(cacheable=true)
    public static List<Categories__c> getCateRecords() 
    {
       
         List<Categories__c> parencategoryobj=[Select Id, Name from Categories__c];
        
        return parencategoryobj;
    }
}
        
       /* @AuraEnabled(cacheable=true)
     public static List<Categories__c> getproductcatrecords(string procatId)
     {
        List<Categories__c> categoryobj;
        if(
            Categories__c.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.Categories__c.fields.Name.isAccessible() && 
            Schema.SObjectType.Categories__c.fields.ParentCategory__c.isAccessible() )
            {
                categoryobj=[Select Id, Name, ParentCategory__c from Categories__c where ParentCategory__c=:procatId];
                for(Categories__c catpro:categoryobj)
                {
                    categoryobj.add(catpro);
                }
            }
            return categoryobj;
        }

             
     @AuraEnabled(cacheable=true)
     public static List<Product_Categories__c> getproduct(string proId)
     {
        List<Product_Categories__c> producateobj;
        if(
            Product_Categories__c.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.Product_Categories__c.fields.Name.isAccessible() && 
            Schema.SObjectType.Product_Categories__c.fields.Category__c.isAccessible() )
            {
                producateobj=[Select Id, Name, Category__c from Product_Categories__c where Category__c=:proId];

                for(Product_Categories__c producatgory:producateobj)
                {
                    producateobj.add(producatgory);  
                }
            }
            return producateobj;
        }
    }*/